
---
  
# Install Java 

- name: Install Java 8
  apt:
   name: openjdk-8-jdk
   state: present
   update_cache: yes

- name: Allow ports ..
  ufw:
          rule: allow
          proto: tcp
          port: "{{item}}"  
  loop:
          - 5601
          - 9200  
